# Параметры TF-IDF модели
tfidf:
  smooth_idf: true              # Сглаживание IDF
  sublinear_tf: false           # Использовать сублинейное масштабирование TF
  max_features: 5000            # Максимальное количество фичей
  min_df: 2                     # Минимальная частота слова
  max_df: 0.95                  # Максимальная частота слова

# Параметры Word2Vec модели
word2vec:
  window_size: 5                # Размер окна контекста
  vector_size: 300              # Размерность вектора
  min_count: 2                  # Минимальная частота слова
  workers: 4                    # Количество потоков
  epochs: 10                    # Количество эпох обучения
